#!/usr/local/bin/python3.10

"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["Shyft.py"]
DATA_FILES = []
OPTIONS = {
    "iconfile": "resources/icon.icns",
    "includes": ["tkinter"],
    "plist": {
        "CFBundleName": "Shyft",
        "CFBundleIdentifier": "com.enclaim.shyft",
        "CFBundleVersion": "0.0.1",
        "CFBundleShortVersionString": "0.1",
        "LSUIElement": True,
        "NSAppTransportSecurity": {"NSAllowsArbitraryLoads": True},
        "CFBundleEntitlementsFile": "entitlements.plist",
        "NSSupportsAutomaticGraphicsSwitching": "true",
        "NSAppSleepDisabled": "true",
        "NSHighResolutionCapable": "true",
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
