"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Shyft.py']
DATA_FILES = ['./resources']
OPTIONS = {
    'iconfile': 'resources/icon.icns',
    'includes': ['tkinter'],
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
